/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuU8g2.h"
#include <RuntimeMenuItem.h>
#include <IoAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx;
extern GraphicsDeviceRenderer renderer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern TextMenuItem menuaboutText3;
extern TextMenuItem menuaboutText2;
extern TextMenuItem menuaboutText1;
extern BackMenuItem menuBackAbout;
extern SubMenuItem menuAbout;
extern BackMenuItem menuBackwirelessMenu;
extern SubMenuItem menuwirelessMenu;
extern BackMenuItem menuBackmotorMenu;
extern SubMenuItem menumotorMenu;
extern BackMenuItem menuBacksettingsMenu;
extern SubMenuItem menusettingsMenu;
extern AnalogMenuItem menubpmMenu;
extern BooleanMenuItem menuplayMenu;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuplayMenu; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION setSpeed(int id);
void CALLBACK_FUNCTION switchPlayStatus(int id);

#endif // MENU_GENERATED_CODE_H
